baseurl = "http://ericmarsh.com/"
languageCode = "en-us"
title = "Eric Marsh Personal Blog"
theme = "casper"
paginate = 20
DisqusShortname = "ericmarsh"
Copyright = "All rights reserved - 2016"
canonifyurls = true

[params]
  description = "My thoughts on software and other stuff"
  cover = "images/beer-1200-max.jpg"
  author = "Eric Marsh"
  authorlocation = "Chicago, IL"
  authorwebsite = "http://erickmarsh.github.io/blog"
  bio= "my bio"
  logo = "images/e-logo.png"
  googleAnalyticsUserID = "UA-18081382-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = "http://feeds.feedburner.com/..." 
  githubName = "erickmarsh"
  twitterName = "marshian"
  # facebookName = ""
  linkedinName = "erickmarsh"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

[[menu.main]]
  name = "My Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "About me"
  weight = -110
  identifier = "about"
  url = "/about"